package dao;

import entity.OutputList;
import utils.queryCondition;

import java.util.List;

public interface OutputListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer outputListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    int insert(OutputList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    int insertSelective(OutputList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    OutputList selectByPrimaryKey(Integer outputListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutputList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutputList record);

    List<OutputList> selectOutputByDate(queryCondition condition);
}