package entity;

import java.util.Date;

public class CpUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_id
     *
     * @mbggenerated
     */
    private Integer cpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_name
     *
     * @mbggenerated
     */
    private String cpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_access_num
     *
     * @mbggenerated
     */
    private String cpAccessNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_account
     *
     * @mbggenerated
     */
    private String cpAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_pwd
     *
     * @mbggenerated
     */
    private String cpPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_company_name
     *
     * @mbggenerated
     */
    private String cpCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_company_addr
     *
     * @mbggenerated
     */
    private String cpCompanyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_status_update_url
     *
     * @mbggenerated
     */
    private String cpStatusUpdateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.verify_status
     *
     * @mbggenerated
     */
    private Integer verifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.sp_id
     *
     * @mbggenerated
     */
    private String spId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_user.cp_attachment_upload
     *
     * @mbggenerated
     */
    private byte[] cpAttachmentUpload;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated
     */
    public CpUser(Integer cpId, String cpName, String cpAccessNum, String cpAccount, String cpPwd, String cpCompanyName, String cpCompanyAddr, String cpStatusUpdateUrl, Date createtime, Integer verifyStatus, String spId, byte[] cpAttachmentUpload) {
        this.cpId = cpId;
        this.cpName = cpName;
        this.cpAccessNum = cpAccessNum;
        this.cpAccount = cpAccount;
        this.cpPwd = cpPwd;
        this.cpCompanyName = cpCompanyName;
        this.cpCompanyAddr = cpCompanyAddr;
        this.cpStatusUpdateUrl = cpStatusUpdateUrl;
        this.createtime = createtime;
        this.verifyStatus = verifyStatus;
        this.spId = spId;
        this.cpAttachmentUpload = cpAttachmentUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_id
     *
     * @return the value of cp_user.cp_id
     *
     * @mbggenerated
     */
    public Integer getCpId() {
        return cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_name
     *
     * @return the value of cp_user.cp_name
     *
     * @mbggenerated
     */
    public String getCpName() {
        return cpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_access_num
     *
     * @return the value of cp_user.cp_access_num
     *
     * @mbggenerated
     */
    public String getCpAccessNum() {
        return cpAccessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_account
     *
     * @return the value of cp_user.cp_account
     *
     * @mbggenerated
     */
    public String getCpAccount() {
        return cpAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_pwd
     *
     * @return the value of cp_user.cp_pwd
     *
     * @mbggenerated
     */
    public String getCpPwd() {
        return cpPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_company_name
     *
     * @return the value of cp_user.cp_company_name
     *
     * @mbggenerated
     */
    public String getCpCompanyName() {
        return cpCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_company_addr
     *
     * @return the value of cp_user.cp_company_addr
     *
     * @mbggenerated
     */
    public String getCpCompanyAddr() {
        return cpCompanyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_status_update_url
     *
     * @return the value of cp_user.cp_status_update_url
     *
     * @mbggenerated
     */
    public String getCpStatusUpdateUrl() {
        return cpStatusUpdateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.createtime
     *
     * @return the value of cp_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.verify_status
     *
     * @return the value of cp_user.verify_status
     *
     * @mbggenerated
     */
    public Integer getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.sp_id
     *
     * @return the value of cp_user.sp_id
     *
     * @mbggenerated
     */
    public String getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_user.cp_attachment_upload
     *
     * @return the value of cp_user.cp_attachment_upload
     *
     * @mbggenerated
     */
    public byte[] getCpAttachmentUpload() {
        return cpAttachmentUpload;
    }
}