package entity;

import java.util.Date;

public class OutputList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.output_list_id
     *
     * @mbggenerated
     */
    private Integer outputListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.cp_id
     *
     * @mbggenerated
     */
    private Integer cpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.link_id
     *
     * @mbggenerated
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.access_num
     *
     * @mbggenerated
     */
    private String accessNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.orderstring_type
     *
     * @mbggenerated
     */
    private Integer orderstringType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.stream_no
     *
     * @mbggenerated
     */
    private String streamNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.correlator
     *
     * @mbggenerated
     */
    private String correlator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column output_list.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output_list
     *
     * @mbggenerated
     */
    public OutputList(Integer outputListId, String userId, Integer cpId, String linkId, String accessNum, Integer orderstringType, Date orderTime, Integer price, String location, String streamNo, String correlator, String productName) {
        this.outputListId = outputListId;
        this.userId = userId;
        this.cpId = cpId;
        this.linkId = linkId;
        this.accessNum = accessNum;
        this.orderstringType = orderstringType;
        this.orderTime = orderTime;
        this.price = price;
        this.location = location;
        this.streamNo = streamNo;
        this.correlator = correlator;
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.output_list_id
     *
     * @return the value of output_list.output_list_id
     *
     * @mbggenerated
     */
    public Integer getOutputListId() {
        return outputListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.user_id
     *
     * @return the value of output_list.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.cp_id
     *
     * @return the value of output_list.cp_id
     *
     * @mbggenerated
     */
    public Integer getCpId() {
        return cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.link_id
     *
     * @return the value of output_list.link_id
     *
     * @mbggenerated
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.access_num
     *
     * @return the value of output_list.access_num
     *
     * @mbggenerated
     */
    public String getAccessNum() {
        return accessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.orderstring_type
     *
     * @return the value of output_list.orderstring_type
     *
     * @mbggenerated
     */
    public Integer getOrderstringType() {
        return orderstringType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.order_time
     *
     * @return the value of output_list.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.price
     *
     * @return the value of output_list.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.location
     *
     * @return the value of output_list.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.stream_no
     *
     * @return the value of output_list.stream_no
     *
     * @mbggenerated
     */
    public String getStreamNo() {
        return streamNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.correlator
     *
     * @return the value of output_list.correlator
     *
     * @mbggenerated
     */
    public String getCorrelator() {
        return correlator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column output_list.product_name
     *
     * @return the value of output_list.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }
}